add drone config

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -11,8 +11,6 @@ on:
       - fix/**
       - pr/**
 
-
-
 jobs:
   posix:
     strategy:
@@ -68,10 +66,11 @@ jobs:
     container: ${{ matrix.container }}
 
     steps:
-      - uses: actions/checkout@v2
       - name: Check if running in container
         if: matrix.container != ''
         run: echo "GHA_CONTAINER=${{ matrix.container }}" >> $GITHUB_ENV
+
+      - uses: actions/checkout@v2
 
       - name: linux
         shell: bash
@@ -89,24 +88,10 @@ jobs:
           TRAVIS_OS_NAME: "linux"
         run: |
           echo '==================================> SETUP'
-          BOOST_CI_ORG=boostorg BOOST_CI_BRANCH=master && wget https://github.com/$BOOST_CI_ORG/boost-ci/archive/$BOOST_CI_BRANCH.tar.gz && tar -xvf $BOOST_CI_BRANCH.tar.gz && mkdir -p .github &&  mv boost-ci-$BOOST_CI_BRANCH .github/boost-ci
           echo '==================================> PACKAGES'
-          set -ex
-          echo "Before package removal or install"
-          whoami
-          dpkg -l
-          echo "Checking /usr/local"
-          ls -al /usr/local
-          echo "Checking clang"
-          which clang++ || true
-          clang++ --version || true
-          ls -al /etc/alternatives
-          ls -al /usr/bin/c*
-          echo "about to run sudo apt-get purge -y $PACKAGES_TO_REMOVE"
+          sudo ln -s /usr/bin/llvm-cov-9 /usr/bin/llvm-cov
+          set -e
           if [ -n "$PACKAGES_TO_REMOVE" ]; then sudo apt-get purge -y $PACKAGES_TO_REMOVE; fi
-          echo "about to run the equivalent of linux-cxx-install.sh"
-
-          set -ex
           echo ">>>>> APT: REPO.."
           for i in {1..3}; do sudo -E apt-add-repository -y "ppa:ubuntu-toolchain-r/test" && break || sleep 2; done
           
@@ -130,16 +115,6 @@ jobs:
           echo ">>>>> APT: INSTALL ${PACKAGES}.."
           sudo -E DEBIAN_FRONTEND=noninteractive apt-get -o Acquire::Retries=3 -y --no-install-suggests --no-install-recommends install ${PACKAGES}
 
-          echo "done with linux-cxx-install.sh"
-          echo "After package removal and install"
-          dpkg -l
-          echo "Checking /usr/local"
-          ls -al /usr/local
-          echo "Checking clang"
-          which clang++ || true
-          clang++ --version || true
-          ls -al /etc/alternatives
-          ls -al /usr/bin/c*
           echo '==================================> INSTALL AND COMPILE'
           set -e
           set -x
@@ -211,7 +186,7 @@ jobs:
           echo $OTHER_LIBS
           eval "$LCOV --remove $TRAVIS_BUILD_DIR/coverals/coverage.info $OTHER_LIBS -o $TRAVIS_BUILD_DIR/coverals/coverage.info"
           cd $TRAVIS_BUILD_DIR
-          gem install coveralls-lcov
+          sudo gem install coveralls-lcov || echo "ERROR. Failed to install coveralls-lcov"
           coveralls-lcov coverals/coverage.info
 
           fi
